export const DEPTS = [
  { id: "ENG", name: "Engineering / Development", short: "Engineering", tint: "dept-eng" },
  { id: "HR", name: "HR & People Operations", short: "HR", tint: "dept-hr" },
  { id: "FIN", name: "Finance & Accounting", short: "Finance", tint: "dept-fin" },
  { id: "MGMT", name: "Management & Leadership", short: "Management", tint: "dept-mgmt" },
  { id: "DESIGN", name: "Design & Marketing", short: "Design", tint: "dept-design" },
]

export const LEVELS = ["Beginner", "Intermediate", "Expert"]

const johnSkills = [
  { name: "Python", level: "Expert" },
  { name: "React", level: "Expert" },
  { name: "AWS", level: "Expert" },
  { name: "Docker", level: "Intermediate" },
  { name: "GraphQL", level: "Intermediate" },
  { name: "Rust", level: "Beginner" },
  { name: "SQL", level: "Beginner" },
]

export function emptyProfile(overrides = {}) {
  return {
    photo: "",
    phone: "",
    city: "",
    dob: "",
    gender: "",
    nationality: "",
    bio: "",
    linkedin: "",
    github: "",
    portfolio: "",
    experience: [],
    skills: [],
    certifications: [],
    education: [],
    projects: [],
    githubRepos: [],
    completeness: 18,
    onboarded: false,
    ...overrides,
  }
}

export function makeEmployees() {
  return [
    {
      id: "emp-john",
      role: "employee",
      email: "john@skillsphere.test",
      password: "demo",
      name: "John Doe",
      employeeId: "ENG-1042",
      department: "ENG",
      title: "Senior Developer",
      joined: "Jan 2021",
      onboarded: true,
      completeness: 87,
      phone: "+91 98450 11220",
      city: "Bangalore",
      dob: "1994-03-12",
      gender: "Male",
      nationality: "Indian",
      bio: "Backend-leaning full-stack engineer. Ships Python services and React consoles, mentors a squad of six, and keeps AWS bills honest.",
      linkedin: "https://linkedin.com/in/johndoe",
      github: "https://github.com/johndoe",
      portfolio: "https://johndoe.dev",
      skills: johnSkills,
      experience: [
        {
          company: "Northclear Labs",
          title: "Senior Developer",
          duration: "2021 — Present",
          responsibilities: "Led a team of 6. Owned matching engine APIs and internal consoles.",
          technologies: "Python, React, AWS, Docker",
          achievements: "Cut p95 latency 40%. Mentored 4 juniors to mid-level.",
        },
        {
          company: "Helio Systems",
          title: "Software Engineer",
          duration: "2018 — 2021",
          responsibilities: "Built REST services and React dashboards for ops.",
          technologies: "Python, React, PostgreSQL",
          achievements: "Shipped the first customer self-serve portal.",
        },
      ],
      certifications: [
        { name: "AWS Solutions Architect Associate", issuer: "Amazon", date: "2023-06", url: "https://aws.amazon.com" },
      ],
      education: [{ degree: "B.E. Computer Science", institution: "NITK", year: "2018", gpa: "8.4" }],
      projects: [
        {
          title: "Cleardeck blotter",
          role: "Tech lead",
          description: "Internal order blotter with live risk.",
          teamSize: "6",
          technologies: "React, Python, WebSockets",
          duration: "8 months",
          outcome: "Used daily by 40 traders in the prototype desk.",
          github: "https://github.com/johndoe/cleardeck",
          demo: "",
          type: "Internal",
        },
      ],
      githubRepos: [
        { name: "cleardeck", lang: "TypeScript", stars: 42 },
        { name: "py-risk", lang: "Python", stars: 18 },
        { name: "infra-cdk", lang: "TypeScript", stars: 7 },
      ],
      roadmaps: [],
      hiddenSkills: ["System Design", "Mentoring"],
    },
    {
      id: "emp-jane",
      role: "employee",
      email: "jane@skillsphere.test",
      password: "demo",
      name: "Jane Smith",
      employeeId: "ENG-1108",
      department: "ENG",
      title: "Senior Developer",
      joined: "Mar 2020",
      onboarded: true,
      completeness: 82,
      city: "Hyderabad",
      phone: "+91 90000 22110",
      bio: "React specialist with CI/CD and design-system work.",
      linkedin: "https://linkedin.com/in/janesmith",
      github: "https://github.com/janesmith",
      portfolio: "",
      skills: [
        { name: "React", level: "Expert" },
        { name: "TypeScript", level: "Expert" },
        { name: "Python", level: "Intermediate" },
        { name: "AWS", level: "Intermediate" },
        { name: "System Design", level: "Expert" },
      ],
      experience: [{ company: "SkillSphere", title: "Senior Developer", duration: "2020 — Present", responsibilities: "Frontend platform", technologies: "React", achievements: "Design system adoption" }],
      certifications: [],
      education: [{ degree: "B.Tech IT", institution: "VIT", year: "2019", gpa: "8.9" }],
      projects: [],
      githubRepos: [],
      roadmaps: [],
      hiddenSkills: ["Mentoring"],
      onboarded: true,
    },
    {
      id: "emp-alice",
      role: "employee",
      email: "alice@skillsphere.test",
      password: "demo",
      name: "Alice Rao",
      employeeId: "ENG-1201",
      department: "ENG",
      title: "Backend Engineer",
      joined: "Jul 2022",
      onboarded: true,
      completeness: 64,
      city: "Pune",
      bio: "Python services, learning ML.",
      skills: [
        { name: "Python", level: "Expert" },
        { name: "SQL", level: "Intermediate" },
        { name: "Docker", level: "Beginner" },
      ],
      experience: [],
      certifications: [],
      education: [],
      projects: [],
      githubRepos: [],
      roadmaps: [],
      hiddenSkills: [],
      linkedin: "",
      github: "",
      portfolio: "",
    },
    {
      id: "emp-bob",
      role: "employee",
      email: "bob@skillsphere.test",
      password: "demo",
      name: "Bob Mehta",
      employeeId: "ENG-1214",
      department: "ENG",
      title: "Developer",
      joined: "Nov 2023",
      onboarded: true,
      completeness: 55,
      city: "Chennai",
      bio: "Full-stack generalist.",
      skills: [
        { name: "React", level: "Intermediate" },
        { name: "Python", level: "Beginner" },
      ],
      experience: [],
      certifications: [],
      education: [],
      projects: [],
      githubRepos: [],
      roadmaps: [],
      hiddenSkills: [],
    },
    {
      id: "emp-ram",
      role: "employee",
      email: "ram@skillsphere.test",
      password: "demo",
      name: "Ram Iyer",
      employeeId: "FIN-304",
      department: "FIN",
      title: "Finance Analyst",
      joined: "Feb 2019",
      onboarded: true,
      completeness: 70,
      city: "Mumbai",
      bio: "FP&A and forecasting.",
      skills: [
        { name: "Excel", level: "Expert" },
        { name: "SQL", level: "Intermediate" },
        { name: "Python", level: "Beginner" },
      ],
      experience: [],
      certifications: [],
      education: [],
      projects: [],
      githubRepos: [],
      roadmaps: [],
      hiddenSkills: [],
    },
    {
      id: "emp-priya",
      role: "employee",
      email: "priya@skillsphere.test",
      password: "demo",
      name: "Priya Shah",
      employeeId: "HR-088",
      department: "HR",
      title: "HR Business Partner",
      joined: "May 2018",
      onboarded: true,
      completeness: 78,
      city: "Bangalore",
      bio: "People partner for engineering orgs.",
      skills: [
        { name: "Employee Relations", level: "Expert" },
        { name: "Talent Development", level: "Expert" },
        { name: "Analytics", level: "Intermediate" },
      ],
      experience: [],
      certifications: [],
      education: [],
      projects: [],
      githubRepos: [],
      roadmaps: [],
      hiddenSkills: [],
    },
  ]
}

export function makeHr() {
  return {
    id: "hr-maya",
    role: "hr",
    email: "hr@skillsphere.test",
    password: "demo",
    name: "Maya Krishnan",
    title: "HR Admin",
    department: "HR",
    onboarded: true,
  }
}

export function makeJobs() {
  return [
    {
      id: "job-techlead",
      title: "Tech Lead",
      department: "ENG",
      type: "Full-time",
      mode: "Hybrid",
      location: "Bangalore",
      minExp: 5,
      skills: ["Python", "React", "AWS", "System Design", "Leadership"],
      jd: "We are looking for a Tech Lead to guide a team of 8 engineers, own system architecture, conduct code reviews, work with stakeholders on roadmap planning, and drive delivery of high-quality software products. You will set engineering standards, partner with product, and still ship.",
      posted: "2026-09-15",
    },
    {
      id: "job-senior",
      title: "Senior Developer",
      department: "ENG",
      type: "Full-time",
      mode: "Hybrid",
      location: "Bangalore",
      minExp: 4,
      skills: ["Python", "React", "AWS", "Docker"],
      jd: "Senior Developer to own services end-to-end: Python APIs, React consoles, AWS deploys, and mentoring. Strong code review culture.",
      posted: "2026-09-12",
    },
    {
      id: "job-ds",
      title: "Data Scientist",
      department: "ENG",
      type: "Full-time",
      mode: "Hybrid",
      location: "Bangalore",
      minExp: 3,
      skills: ["Python", "Machine Learning", "TensorFlow", "Statistics", "AWS SageMaker", "SQL"],
      jd: "We are looking for a Data Scientist with 3+ years of experience in ML model development, statistical analysis, Python (NumPy, Pandas, Scikit-learn), TensorFlow/PyTorch, and experience deploying models on AWS SageMaker.",
      posted: "2026-09-10",
    },
    {
      id: "job-ml",
      title: "ML Engineer",
      department: "ENG",
      type: "Full-time",
      mode: "Remote",
      location: "India",
      minExp: 3,
      skills: ["Python", "MLOps", "PyTorch", "Kubernetes", "AWS"],
      jd: "Productionize models, build training pipelines, and own inference SLAs.",
      posted: "2026-09-08",
    },
    {
      id: "job-fe",
      title: "Frontend Developer",
      department: "ENG",
      type: "Full-time",
      mode: "Office",
      location: "Bangalore",
      minExp: 2,
      skills: ["React", "TypeScript", "CSS", "System Design"],
      jd: "Build dense product UIs with React. Design-system fluency required.",
      posted: "2026-09-05",
    },
    {
      id: "job-fin",
      title: "Finance Analyst",
      department: "FIN",
      type: "Full-time",
      mode: "Hybrid",
      location: "Mumbai",
      minExp: 2,
      skills: ["Excel", "SQL", "Forecasting", "Accounting"],
      jd: "FP&A partner for product lines. Monthly close support and scenario models.",
      posted: "2026-09-14",
    },
    {
      id: "job-hrbp",
      title: "HR Business Partner",
      department: "HR",
      type: "Full-time",
      mode: "Hybrid",
      location: "Bangalore",
      minExp: 4,
      skills: ["Employee Relations", "Talent Development", "Analytics"],
      jd: "HRBP for a 70-person engineering org. Coaching managers, workforce plans, and L&D.",
      posted: "2026-09-18",
    },
    {
      id: "job-pm",
      title: "Product Manager",
      department: "MGMT",
      type: "Full-time",
      mode: "Hybrid",
      location: "Bangalore",
      minExp: 5,
      skills: ["Roadmapping", "Stakeholder Management", "Analytics", "SQL"],
      jd: "Own the talent-marketplace roadmap. Tight loop with engineering and HR ops.",
      posted: "2026-09-11",
    },
  ]
}

export function makeAssessments() {
  return [
    {
      id: "as-john-tl",
      employeeId: "emp-john",
      jobId: "job-techlead",
      date: "2026-09-19",
      time: "10:00",
      duration: 30,
      status: "upcoming",
      questions: [],
      answers: {},
      score: null,
      feedback: "",
      notifyEmail: true,
      notifyInApp: true,
    },
    {
      id: "as-john-senior",
      employeeId: "emp-john",
      jobId: "job-senior",
      date: "2026-09-18",
      time: "11:00",
      duration: 30,
      status: "accepted",
      questions: [],
      answers: {},
      score: 24,
      total: 30,
      feedback: "HR will contact you about next steps.",
    },
    {
      id: "as-john-fe",
      employeeId: "emp-john",
      jobId: "job-fe",
      date: "2026-09-10",
      time: "09:00",
      duration: 30,
      status: "rejected",
      questions: [],
      answers: {},
      score: 16,
      total: 30,
      feedback: "Strong in React but system design needs improvement.",
    },
    {
      id: "as-jane-senior",
      employeeId: "emp-jane",
      jobId: "job-senior",
      date: "2026-09-20",
      time: "10:00",
      duration: 30,
      status: "pending_review",
      questions: [],
      answers: {},
      score: 27,
      total: 30,
      summary: "Strong React and system design. Weak in CI/CD pipeline concepts (2/4 correct). Recommended for acceptance.",
    },
    {
      id: "as-tom-senior",
      employeeId: "emp-bob",
      jobId: "job-senior",
      date: "2026-09-20",
      time: "14:00",
      duration: 30,
      status: "pending_review",
      questions: [],
      answers: {},
      score: 15,
      total: 30,
      summary: "Needs more depth on AWS and service ownership.",
    },
  ]
}

export function parseResumeFromFile(fileName = "") {
  return {
    name: "John Doe",
    email: "john@skillsphere.test",
    phone: "+91 98450 11220",
    city: "Bangalore",
    dob: "1994-03-12",
    gender: "Male",
    nationality: "Indian",
    bio: `Parsed from ${fileName || "resume.pdf"}: Senior developer with Python, React, and AWS. Led a team of six. Interested in platform and talent-systems work.`,
    linkedin: "https://linkedin.com/in/johndoe",
    github: "https://github.com/johndoe",
    portfolio: "https://johndoe.dev",
    skills: johnSkills,
    experience: [
      {
        company: "Northclear Labs",
        title: "Senior Developer",
        duration: "2021 — Present",
        responsibilities: "Led a team of 6 on internal trading and talent tools.",
        technologies: "Python, React, AWS",
        achievements: "Mentored four engineers.",
      },
    ],
    education: [{ degree: "B.E. Computer Science", institution: "NITK", year: "2018", gpa: "8.4" }],
    certifications: [{ name: "AWS SAA", issuer: "Amazon", date: "2023-06", url: "" }],
  }
}

export function initialState() {
  const employees = makeEmployees()
  const hr = [makeHr()]
  return {
    users: [...employees, ...hr],
    jobs: makeJobs(),
    assessments: makeAssessments(),
    sessionId: null,
    chats: {
      "emp-john": [
        {
          from: "bot",
          text: "Hi John! I know your profile well. Ask me anything about your career, skills, market trends, or job opportunities.",
        },
      ],
    },
    notices: [],
  }
}
